title: Discover
logo: /assets/img/190804_logo_discover.svg
description: Design optimization tool built for Rhino Grasshopper
release_link: https://www.dropbox.com/s/4ewmablz1anjzfh/discover-190910.zip?dl=1
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
