title: Discover
logo: /assets/img/190804_logo_discover.svg
description: Design optimization tool built for Rhino Grasshopper
release_link: https://www.dropbox.com/s/0v9d4iu1z1e6mj6/discover-190822.zip?dl=1
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal