title: Discover
logo: /assets/img/200406_discover_logo.svg
description: Design optimization tool built for Rhino Grasshopper
release_link: https://www.dropbox.com/s/ct2bgz3ud5vniwa/Discover-2004.zip?dl=1
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
