title: Discover
logo: /assets/img/190804_logo_discover.svg
description: Design optimization tool built for Rhino Grasshopper
release_link: https://www.dropbox.com/s/qp3hlor2ofrkouf/Discover-1912.zip?dl=1
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
