title: Discover
logo: /assets/img/200406_discover_logo.svg
description: Design optimization tool built for Rhino Grasshopper
release_link: https://www.dropbox.com/s/rkpqplf4blme9is/Discover-2101.zip?dl=1
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
